In [73]:
import pandas as pd
import itertools

import numpy as np
import matplotlib.pyplot as plt
import time
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB,BernoulliNB, MultinomialNB
from sklearn.neighbors import KernelDensity

In [74]:
train_data = pd.read_csv("data/d5.csv")
test_data = pd.read_csv("data/d4.csv")

corr = train_data.corr()
corr.style.background_gradient()

In [75]:
train_data.head()

Jobs_per_ 1Minute  Jobs_per_ 5 Minutes  Jobs_per_ 15Minutes  Mem capacity  \
0              7.000                7.455                7.727            12   
1              3.600                4.800                5.800            12   
2              3.455                4.909                5.818            12   
3              4.455                5.273                5.909            12   
4              3.500                5.100                5.900            12   

   Disk_capacity_GB  Num_of_CPU_Cores  CPU_speed_per_Core  Avg_Recieve_Kbps  \
0         128.72872                 6                   1            31.248   
1         128.72872                 6                   1            31.248   
2         128.72872                 6                   1            31.248   
3         128.72872                 6                   1            31.248   
4         128.72872                 6                   1            31.248   

   Avg_Transmit_Kbps  Class_Name  
0             31.248  'Very Low'  
1             31.248  'Very Low'  
2             31.248  'Very Low'  
3             31.248  'Very Low'  
4             31.248  'Very Low'

In [76]:
X_train= train_data
X_test = test_data

In [77]:
gnb = GaussianNB()
used_features =[
    "Jobs_per_ 1Minute",
    "Jobs_per_ 5 Minutes",
    "Jobs_per_ 15Minutes",
    "Mem capacity",
    "Disk_capacity_GB",
    "Num_of_CPU_Cores",
    "CPU_speed_per_Core",
    "Avg_Recieve_Kbps",
    "Avg_Transmit_Kbps"
]

In [78]:
gnb.fit(
    X_train[used_features].values,
    X_train["Class_Name"]
)
y_pred = gnb.predict(X_test[used_features])
y_pred

array(["'Low'", "'Low'", "'Low'", ..., "'Very Low'", "'Very Low'",
       "'Very Low'"], dtype='<U10')

In [79]:
print("Number of mislabeled points out of a total {} points : {}, performance {:05.2f}%"
      .format(
          X_test.shape[0],
          (X_test["Class_Name"] != y_pred).sum(),
          100*(1-(X_test["Class_Name"] != y_pred).sum()/X_test.shape[0])
))

Number of mislabeled points out of a total 2450 points : 2302, performance 06.04%


In [80]:
cnf_matrix = confusion_matrix(X_test["Class_Name"],y_pred)
cnf_matrix

array([[   0, 1027,    7,    0, 1246],
       [   0,  148,    2,    0,    0],
       [   0,    0,    0,    0,    0],
       [   0,    2,    0,    0,    2],
       [   9,    6,    1,    0,    0]], dtype=int64)

In [81]:
b=cnf_matrix / cnf_matrix.astype(np.float).sum(axis=1)
b

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.00000000e+00, 6.84666667e+00,            inf, 0.00000000e+00,
        7.78750000e+01],
       [0.00000000e+00, 9.86666667e-01,            inf, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00,            nan, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 1.33333333e-02,            nan, 0.00000000e+00,
        1.25000000e-01],
       [3.94736842e-03, 4.00000000e-02,            inf, 0.00000000e+00,
        0.00000000e+00]])

In [82]:
np.round(b,2)

array([[0.000e+00, 6.850e+00,       inf, 0.000e+00, 7.788e+01],
       [0.000e+00, 9.900e-01,       inf, 0.000e+00, 0.000e+00],
       [0.000e+00, 0.000e+00,       nan, 0.000e+00, 0.000e+00],
       [0.000e+00, 1.000e-02,       nan, 0.000e+00, 1.200e-01],
       [0.000e+00, 4.000e-02,       inf, 0.000e+00, 0.000e+00]])

In [83]:
# Plot normalized confusion matrix
plt.figure()
plot_confusion_matrix(cnf_matrix, normalize=True,
                      title='Normalized confusion matrix')

plt.show()

NameError: name 'plot_confusion_matrix' is not defined

<Figure size 432x288 with 0 Axes>

In [ ]:
X=np.linspace(0,500,20)
